# Generated by Django 3.0.3 on 2020-02-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackForms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='csv_file',
            field=models.FilePathField(path='/media/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='data',
            field=models.FilePathField(path='/media/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='empty_form',
            field=models.FilePathField(path='/media/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='zip_file',
            field=models.FilePathField(path='/media/'),
        ),
    ]
