# Generated by Django 3.0.3 on 2020-02-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackForms', '0002_auto_20200216_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='csv_file',
            field=models.FileField(upload_to='E:\\projects\\HackFormsWeb\\media/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='data',
            field=models.FileField(upload_to='E:\\projects\\HackFormsWeb\\media/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='empty_form',
            field=models.FileField(upload_to='E:\\projects\\HackFormsWeb\\media/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='zip_file',
            field=models.FileField(upload_to='E:\\projects\\HackFormsWeb\\media/'),
        ),
    ]
