# Generated by Django 3.0.3 on 2020-02-23 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HackForms', '0003_auto_20200217_1637'),
        ('HackForms', '0003_auto_20200217_1130'),
    ]

    operations = [
    ]
