# Generated by Django 2.2.2 on 2020-02-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackForms', '0005_auto_20200223_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='csv_file',
            field=models.FileField(upload_to='C:\\Users\\kiran\\PycharmProjects\\HackFormsWeb\\media'),
        ),
    ]
